### ISSUE TITLE
expecting Pfam models not in the current release? 

### ISSUE THREAD

**Issue by hyphaltip** [metashot/prok-classify#1]
Is there a specific version of gtkdb one should use - the documentation does not indicate this
```
Command output:
  [2022-08-01 17:07:50] INFO: GTDB-Tk v1.5.0
  [2022-08-01 17:07:50] INFO: gtdbtk align --identify_dir identify_dir --out_dir gtdbtk --cpus 32
  [2022-08-01 17:07:50] INFO: Using GTDB-Tk reference data version r207: 207
  [2022-08-01 17:07:51] ERROR: Uncontrolled exit resulting from an unexpected error.

  ================================================================================
  EXCEPTION: FileNotFoundError
    MESSAGE: [Errno 2] No such file or directory: '207/markers/pfam/individual_hmms/PF01868.17.hmm'
  ________________________________________________________________________________
```

**Comment by hyphaltip** [comment]
to use explicitly release r202 need to give the specific release URL I think https://data.gtdb.ecogenomic.org/releases/release202/202.0/auxillary_files/gtdbtk_r202_data.tar.gz
however I still get errors 

```
Uncontrolled exit resulting from an unexpected error.

================================================================================
EXCEPTION: IndexError
  MESSAGE: list index out of range
________________________________________________________________________________

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gtdbtk/__main__.py", line 95, in main
    gt_parser.parse_options(args)
  File "/usr/local/lib/python3.7/dist-packages/gtdbtk/main.py", line 722, in parse_options
    self.align(options)
  File "/usr/local/lib/python3.7/dist-packages/gtdbtk/main.py", line 290, in align
    self.genomes_to_process)
  File "/usr/local/lib/python3.7/dist-packages/gtdbtk/markers.py", line 567, in align
    len(list(user_msa.values())[0]),
IndexError: list index out of range
```

**Comment by davidealbanese** [comment]
Dear @hyphaltip,
I apologize for the delay. Prok-classify 1.2.1 (gtdb-tk 1.5.0) requires the gtdb r202 reference files (https://data.gtdb.ecogenomic.org/releases/release202/202.0/auxillary_files/gtdbtk_r202_data.tar.gz). I will update the documentation as soon as possible. 

Please show me the command that led you to have the error.

Prok-classify will soon be integrated into the prok-quality workflow.
